// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bangazon_BE.Migrations
{
    [DbContext(typeof(Bangazon_BEDbContext))]
    [Migration("20241013215103_AddedCartQuantityToProduct")]
    partial class AddedCartQuantityToProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bangazon_BE.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apparel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Bangazon_BE.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DatePlaced")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("OrderNum")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Bangazon_BE.Models.PaymentTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Debit Card"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Apple Pay"
                        });
                });

            modelBuilder.Entity("Bangazon_BE.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartQuantity = 0,
                            CategoryId = 1,
                            Description = "The iPad is a versatile tablet designed for work, play, and everything in between. With its large, high-resolution display, powerful performance, and wide range of apps, the iPad offers a seamless and intuitive user experience.",
                            ImageUrl = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-ipad-wifi-gold-2020?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1626464533000",
                            Name = "IPad",
                            Price = 349.99m,
                            Quantity = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CartQuantity = 0,
                            CategoryId = 1,
                            Description = "Enjoy your music wirelessly with these comfortable and stylish headphones. Featuring long battery life and clear audio, these headphones are perfect for everyday use.",
                            ImageUrl = "https://i5.walmartimages.com/seo/SoundPlay-Foldable-Wireless-Headphones-Bluetooth-Over-Ear-Headset-with-Built-in-Mic-White_7781a45d-3746-4e57-9448-ed352177f124.e514a94af242606cd9abd487ef2bf27f.png",
                            Name = "Wireless Headphones",
                            Price = 79.99m,
                            Quantity = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CartQuantity = 0,
                            CategoryId = 1,
                            Description = "Stay connected and on top of your health with this feature-packed smartwatch. Track your steps, receive notifications, and monitor your heart rate with ease.",
                            ImageUrl = "https://i5.walmartimages.com/seo/Smart-Watch-for-Android-and-iPhone-GTS5-IP68-Waterproof-Smartwatch-for-Women-Men-Smart-Watch-with-Bluetooth-Call-Answer-Make-Calls-Black_084aef55-da45-4f80-8e20-0bcc88accf94.192b2ddc4da4c9d85d0acec2873d72b9.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
                            Name = "Smartwatch",
                            Price = 249.99m,
                            Quantity = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CartQuantity = 0,
                            CategoryId = 1,
                            Description = "A powerful and portable laptop perfect for work, school, or entertainment. With a fast processor, plenty of RAM, and a long-lasting battery, this laptop can handle all your needs.",
                            ImageUrl = "https://i.pcmag.com/imagery/roundups/02naaOkVLe7DIiejFUyDPJp-51..v1700149111.jpg",
                            Name = "Laptop",
                            Price = 799.99m,
                            Quantity = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CartQuantity = 0,
                            CategoryId = 1,
                            Description = "Experience the latest and greatest games on this powerful gaming console. With stunning graphics, immersive gameplay, and a wide variety of games to choose from, this console is perfect for gamers of all ages.",
                            ImageUrl = "https://media.wired.com/photos/644c0d3282d37ced55dff3b3/191:100/w_2580,c_limit/Polymega-Retro-Console-New-Gear.png",
                            Name = "Gaming Console",
                            Price = 499.99m,
                            Quantity = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CartQuantity = 0,
                            CategoryId = 2,
                            Description = "A comfortable and stylish T-shirt perfect for everyday wear.",
                            ImageUrl = "https://cricut.com/dw/image/v2/BHBM_PRD/on/demandware.static/-/Sites-cricut-master-catalog/default/dw7481f5db/images//m/e/mens-tshirt.jpg?sw=527&q=65",
                            Name = "T-Shirt",
                            Price = 19.99m,
                            Quantity = 20,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CartQuantity = 0,
                            CategoryId = 2,
                            Description = "Classic and versatile jeans that can be dressed up or down.",
                            ImageUrl = "https://lsco.scene7.com/is/image/lsco/726930130-front-pdp-ld?fmt=jpeg&qlt=70&resMode=sharp2&fit=crop,1&op_usm=0.6,0.6,8&wid=2000&hei=1840",
                            Name = "Jeans",
                            Price = 49.99m,
                            Quantity = 18,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CartQuantity = 0,
                            CategoryId = 2,
                            Description = "A beautiful and elegant dress perfect for a special occasion.",
                            ImageUrl = "https://i.etsystatic.com/11654563/r/il/f0a012/2284893260/il_570xN.2284893260_e69o.jpg",
                            Name = "Dress",
                            Price = 79.99m,
                            Quantity = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CartQuantity = 0,
                            CategoryId = 2,
                            Description = "Stay cool and stylish at the beach with this fashionable swimsuit.",
                            ImageUrl = "https://i5.walmartimages.com/seo/Bathing-Suit-One-Piece-Swimsuit-Women-Tummy-Control-Tan-Through-Swimwear-Swim-Suits-2024-Underwire-Swimsuits-WomenWomen-s-One-Piece-Ladies-Print-Slin_3af14c03-1be4-40f6-985a-a0702ef91e71.9d8b4c215ec999af05d91e7d615c9f4c.jpeg",
                            Name = "Swimsuit",
                            Price = 39.99m,
                            Quantity = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CartQuantity = 0,
                            CategoryId = 2,
                            Description = "Stay warm and stylish with this trendy jacket.",
                            ImageUrl = "https://i5.walmartimages.com/seo/Lovskoo-Men-Casual-Solid-Turn-down-Collar-Zipper-Padded-Thermal-Jacket-Coat-Men-s-Casual-Canvas-Cotton-Military-Lapel-Jacket-jackets-for-men_5f152a14-c8a1-4f1e-a206-eb34d77d18b5.e3c455b857167493744cc214332d4ecc.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
                            Name = "Jacket",
                            Price = 99.99m,
                            Quantity = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CartQuantity = 0,
                            CategoryId = 3,
                            Description = "A comfortable and stylish sofa perfect for your living room.",
                            ImageUrl = "https://www.ikea.com/us/en/images/products/linanaes-sofa-vissle-beige__1013895_pe829449_s5.jpg",
                            Name = "Sofa",
                            Price = 799.99m,
                            Quantity = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CartQuantity = 0,
                            CategoryId = 3,
                            Description = "A durable and functional kitchen table for your dining area.",
                            ImageUrl = "https://images.thdstatic.com/productImages/350ff1f3-a013-412a-b69e-27845a09e678/svn/rustic-brown-yofe-dining-room-sets-camybn-gi68130w1162-diningset01-64_600.jpg",
                            Name = "Kitchen Table",
                            Price = 299.99m,
                            Quantity = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CartQuantity = 0,
                            CategoryId = 3,
                            Description = "Enjoy outdoor grilling with this high-quality garden grill.",
                            ImageUrl = "https://images.thdstatic.com/productImages/8f9d513c-8eba-4dcf-a03c-a434717bcf23/svn/outsunny-portable-charcoal-grills-846-022-c3_600.jpg",
                            Name = "Grill",
                            Price = 149.99m,
                            Quantity = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CartQuantity = 0,
                            CategoryId = 3,
                            Description = "Add a touch of nature to your home with these beautiful indoor plants.",
                            ImageUrl = "https://www.gardendesign.com/pictures/images/675x529Max/site_3/beautifall-summer-nights-pothos-pothos-plant-proven-winners_18890.jpg",
                            Name = "Indoor Plants",
                            Price = 29.99m,
                            Quantity = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CartQuantity = 0,
                            CategoryId = 3,
                            Description = "Stylish curtains to add privacy and elegance to your home.",
                            ImageUrl = "https://assets.wfcdn.com/im/64527317/compr-r85/2714/271471348/birglinde-blackout-curtains-linen-textured-100-blackout-drapes-for-bedroom-living-room-curtains-clip-ring.jpg",
                            Name = "Curtains",
                            Price = 49.99m,
                            Quantity = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CartQuantity = 0,
                            CategoryId = 4,
                            Description = "Hydrate and nourish your skin with this luxurious moisturizer.",
                            ImageUrl = "https://www.elfcosmetics.com/dw/image/v2/BBXC_PRD/on/demandware.static/-/Sites-elf-master/default/dwf444ad04/2023/HHGelYeahMoisturizer/57430_Closed_R.jpg?sfrm=png&sw=425&q=90",
                            Name = "Moisturizer",
                            Price = 24.99m,
                            Quantity = 25,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CartQuantity = 0,
                            CategoryId = 4,
                            Description = "Achieve a flawless complexion with this high-coverage foundation.",
                            ImageUrl = "https://i5.walmartimages.com/seo/e-l-f-Flawless-Satin-Foundation-Bisque-0-68-fl-oz_32d4d488-a5ad-416e-9927-1cf6c3ffc272.96602d023df5b15290f2bf01fb5cbccf.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
                            Name = "Foundation",
                            Price = 29.99m,
                            Quantity = 20,
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CartQuantity = 0,
                            CategoryId = 4,
                            Description = "Gentle and nourishing shampoo for healthy hair.",
                            ImageUrl = "https://tphbytaraji.com/cdn/shop/products/TPH_HolidayGiftGuide_HolidayFavorites_Honey-fresh.jpg?v=1640471590",
                            Name = "Shampoo",
                            Price = 12.99m,
                            Quantity = 30,
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CartQuantity = 0,
                            CategoryId = 4,
                            Description = "Indulge in a captivating fragrance with this luxurious perfume.",
                            ImageUrl = "https://www.sephora.com/productimages/sku/s513176-main-zoom.jpg",
                            Name = "Perfume",
                            Price = 79.99m,
                            Quantity = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CartQuantity = 0,
                            CategoryId = 4,
                            Description = "Support your health with these essential vitamins and supplements.",
                            ImageUrl = "https://static.slickdealscdn.com/attachment/1/1/3/3/5/6/0/13788248.attach",
                            Name = "Vitamins",
                            Price = 39.99m,
                            Quantity = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            CartQuantity = 0,
                            CategoryId = 5,
                            Description = "A historical fiction novel that follows a group of female mathematicians and engineers who work at NASA during the early days of the space race. It explores themes of gender equality, scientific discovery, and the human spirit.",
                            ImageUrl = "https://media.npr.org/assets/img/2021/08/13/711gd93ifkl_custom-80dd66e555a05cf605f043ca0095760a75d41be4.jpeg?s=1100&c=50&f=jpeg",
                            Name = "The Calculating Stars",
                            Price = 19.99m,
                            Quantity = 25,
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            CartQuantity = 0,
                            CategoryId = 5,
                            Description = "Improve your life and reach your goals with this insightful self-help book that teaches readers how to build good habits and break bad ones. By focusing on small, incremental changes, readers can create lasting positive transformations in their lives.",
                            ImageUrl = "https://media.licdn.com/dms/image/D4D12AQHZJRikGoFIKw/article-cover_image-shrink_720_1280/0/1696425885734?e=2147483647&v=beta&t=GpXawCAMJqzTZw1qYtR5FJNCAITvrAxqFTSrW9q7jdw",
                            Name = "Atomic Habits",
                            Price = 24.99m,
                            Quantity = 18,
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CartQuantity = 0,
                            CategoryId = 5,
                            Description = "A children's book that hilariously flips the script on picky eaters. Three determined kids challenge their parents to try one bite of healthy food, leading to comical reactions and unexpected discoveries about the joys of trying new things.",
                            ImageUrl = "https://placeholder.com/300x300/007bff/fff",
                            Name = "Just Try One Bite",
                            Price = 14.99m,
                            Quantity = 30,
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CartQuantity = 0,
                            CategoryId = 5,
                            Description = "Explore new flavors and cuisines from around the world with this international cookbook.",
                            ImageUrl = "https://i.ebayimg.com/images/g/3pMAAOSwSMJjkLyW/s-l1200.webp",
                            Name = "Betty Crocker's International Cookbook",
                            Price = 29.99m,
                            Quantity = 15,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Bangazon_BE.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Seller")
                        .HasColumnType("boolean");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            Seller = false,
                            Uid = "",
                            Username = "bgore268"
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            Seller = true,
                            Uid = "",
                            Username = "brianagore"
                        });
                });

            modelBuilder.Entity("OrdersProducts", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.Property<int>("ordersId")
                        .HasColumnType("integer");

                    b.HasKey("ProductsId", "ordersId");

                    b.HasIndex("ordersId");

                    b.ToTable("OrdersProducts");
                });

            modelBuilder.Entity("Bangazon_BE.Models.Orders", b =>
                {
                    b.HasOne("Bangazon_BE.Models.PaymentTypes", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId");

                    b.HasOne("Bangazon_BE.Models.Users", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bangazon_BE.Models.Products", b =>
                {
                    b.HasOne("Bangazon_BE.Models.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon_BE.Models.Users", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrdersProducts", b =>
                {
                    b.HasOne("Bangazon_BE.Models.Products", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon_BE.Models.Orders", null)
                        .WithMany()
                        .HasForeignKey("ordersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bangazon_BE.Models.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Bangazon_BE.Models.Users", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
